image:
  name: node:latest
  entrypoint:
    - /usr/bin/env

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - android
    - /android
    # or with Yarn:
    #- .yarn

stages:
  - build

before_script:
  - apt update
  - apt install -y openjdk-17-jdk curl unzip
  - npm ci --cache .npm
  - mkdir -p /android/sdk
  - curl https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -o cmdtools.zip
  - unzip cmdtools.zip
  - echo "y" | ./cmdline-tools/bin/sdkmanager --sdk_root=/android/sdk --install "platforms;android-30"
  - echo "y" | ./cmdline-tools/bin/sdkmanager --sdk_root=/android/sdk --install "build-tools;30.0.3"

eas-build:
  stage: build
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk
  script:
    - npx expo prebuild
    - cd android
    - ANDROID_HOME=/android/sdk ./gradlew assembleRelease